sonar.projectKey=softwareone-platform_mpt-adobe-vipm-ef-extension
sonar.organization=softwareone-mpt-github

sonar.language=py

sonar.sources=mpt_adobe_vipm_ef
sonar.tests=tests
sonar.inclusions=mpt_adobe_vipm_ef/**
sonar.exclusions=tests/**,**/__init__.py

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3
