apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  SDK_EXTENSION_URL: {{ .Values.global.SdkExtensionUrl | quote }}
  SDK_EXTENSION_ID: {{ .Values.global.SdkExtensionId | quote }}
  MPT_API_BASE_URL: {{ .Values.global.mptPublicApiUrl | quote }}
  MPT_PRODUCTS_IDS: {{ .Values.global.MpProductsIds | quote }}
  EXT_ADOBE_API_BASE_URL: {{ .Values.global.AdobeApiEndpoint | quote }}
  EXT_ADOBE_AUTH_ENDPOINT_URL: {{ .Values.global.AdobeAuthEndpoint | quote }}
  EXT_PRODUCT_SEGMENTS: {{ .Values.global.ProductSegments | quote }}
  SDK_OBSERVABILITY_ENABLED: {{ .Values.global.ObservabilityEnabled | quote }}
  SDK_OTEL_SERVICE_NAME: {{ .Values.global.OtelServiceName | quote }}
  LOG_LEVEL: {{ .Values.global.LogLevel | quote }}
  SDK_ZITI_WORKERS: {{ .Values.global.ZitiWorkers | quote }}
