apiVersion: v2
name: mpt-adobe-vipm-ef-extension-app
description: Adobe VIPM EF extension workload (single OpenZiti process)
type: application

# Cli Version: 2.4.0

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 1.0.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: "6.0.0"
